import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-container": "#aaadaf",
        "on-tertiary": "#ffffff",
        "tertiary": "#272b2d",
        "tertiary-container": "#3d4143",
        "primary": "#00236f",
        "on-primary-fixed": "#00164e",
        "surface": "#eef2f8",
        "surface-container": "#dde5f2",
        "secondary": "#006591",
        "on-secondary-fixed": "#001e2f",
        "on-primary-fixed-variant": "#264191",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-background": "#0b1c30",
        "outline": "#757682",
        "background": "#eef2f8",
        "surface-container-highest": "#ccd8ec",
        "secondary-fixed-dim": "#89ceff",
        "surface-dim": "#bfccdf",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#004c6e",
        "secondary-fixed": "#c9e6ff",
        "inverse-primary": "#b6c4ff",
        "on-tertiary-fixed-variant": "#444749",
        "inverse-surface": "#213145",
        "surface-container-high": "#d5e0f0",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#444651",
        "on-error-container": "#93000a",
        "on-primary-container": "#90a8ff",
        "on-secondary-container": "#004666",
        "secondary-container": "#39b8fd",
        "surface-variant": "#d5e0f0",
        "surface-container-low": "#e6ecf6",
        "surface-container-lowest": "#f4f7fc",
        "primary-fixed": "#dce1ff",
        "on-tertiary-fixed": "#191c1e",
        "error": "#ba1a1a",
        "surface-tint": "#4059aa",
        "primary-container": "#1e3a8a",
        "tertiary-fixed": "#e0e3e5",
        "primary-fixed-dim": "#b6c4ff",
        "outline-variant": "#c5c5d3",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-surface": "#0b1c30",
        "surface-bright": "#f4f7fc",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        lg: "24px",
        xs: "4px",
        xl: "40px",
        unit: "4px",
        md: "16px",
        gutter: "20px",
        "container-max": "1280px",
        sm: "8px",
      },
      fontFamily: {
        "label-bold": ["Public Sans", "sans-serif"],
        "headline-md": ["Public Sans", "sans-serif"],
        "display-lg": ["Public Sans", "sans-serif"],
        "body-base": ["Public Sans", "sans-serif"],
        "data-tabular": ["Public Sans", "sans-serif"],
        "title-sm": ["Public Sans", "sans-serif"],
        "body-sm": ["Public Sans", "sans-serif"],
        "public-sans": ["Public Sans", "sans-serif"],
      },
      fontSize: {
        "label-bold": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-base": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-tabular": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
